// <auto-generated />
namespace BikeDekho_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class init170420 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init170420));
        
        string IMigrationMetadata.Id
        {
            get { return "202004170631188_init170420"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
