//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESULTportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> SID { get; set; }
        public string sname { get; set; }
        public string email { get; set; }
        public Nullable<int> semister { get; set; }
        public string Branch { get; set; }
        public Nullable<double> pointer { get; set; }
        public string pssd { get; set; }
    }
}
