// <auto-generated />
namespace OnlineTermWorkSubmission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init030320 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init030320));
        
        string IMigrationMetadata.Id
        {
            get { return "202003022133530_init030320"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
