// <auto-generated />
namespace OnlineTermWorkSubmission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init290220 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init290220));
        
        string IMigrationMetadata.Id
        {
            get { return "202002291416529_init290220"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
